<?xml version="1.0" encoding="utf-8"?><Database Name="prepare for wedding" Class="prepare_for_weddingDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.;Initial Catalog=&quot;prepare for wedding&quot;;Persist Security Info=True;User ID=weddinguser" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="prepare_for_weddingConnectionString2" Provider="System.Data.SqlClient" />
  <Table Name="dbo.tb婚礼信息" Member="tb婚礼信息">
    <Type Name="tb婚礼信息">
      <Column Name="iid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="rowver" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="createtime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="bridegroom" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="bride" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="dateofmarriage" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="lovestroy" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="address" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb祝福" Member="tb祝福">
    <Type Name="tb祝福">
      <Column Name="iid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="rowver" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="createtime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="婚礼iid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="祝福人" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="祝福内容" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb捧场人员信息" Member="tb捧场人员信息">
    <Type Name="tb捧场人员信息">
      <Column Name="iid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="rowver" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="createtime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="婚礼iid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="姓名" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="电话" Type="System.String" DbType="NVarChar(20) NOT NULL" CanBeNull="false" />
      <Column Name="邮箱" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="附言" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.tb评论" Member="tb评论">
    <Type Name="tb评论">
      <Column Name="iid" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="rowver" Type="System.Data.Linq.Binary" DbType="rowversion NOT NULL" CanBeNull="false" IsVersion="true" />
      <Column Name="createtime" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="祝福iid" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="评论人" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="评论内容" Type="System.String" DbType="NVarChar(300)" CanBeNull="true" />
    </Type>
  </Table>
</Database>